"""JRDB PointPillar v2 constants shared by ONNX export and C++ runtime."""

# jrdb_v2_bs8 (pointpillar_v2.yaml)
POINT_CLOUD_RANGE = [-25.6, -25.6, -2.0, 25.6, 25.6, 4.0]
VOXEL_SIZE = [0.128, 0.128, 6.0]
MAX_POINTS_PER_VOXEL = 32
MAX_VOXELS = 50000

CLASS_NAMES = ['Pedestrian']
NUM_CLASSES = 1
NUM_ANCHORS = 4
NUM_DIR_BINS = 4
FEATURE_MAP_STRIDE = 2

ANCHOR_SIZES = [0.93, 0.51, 1.89]  # l, w, h
ANCHOR_ROTATIONS = [0.0, 0.78539816, 1.57079633, 2.35619449]
ANCHOR_BOTTOM_HEIGHT = -0.95

SCORE_THRESH = 0.25
NMS_THRESH = 0.15
DIR_OFFSET = 0.78539

GRID_X = int(round((POINT_CLOUD_RANGE[3] - POINT_CLOUD_RANGE[0]) / VOXEL_SIZE[0]))
GRID_Y = int(round((POINT_CLOUD_RANGE[4] - POINT_CLOUD_RANGE[1]) / VOXEL_SIZE[1]))
DENSE_SHAPE = [GRID_Y, GRID_X]

FEAT_X = GRID_X // FEATURE_MAP_STRIDE
FEAT_Y = GRID_Y // FEATURE_MAP_STRIDE

NUM_CLS_CHANNELS = NUM_ANCHORS * NUM_CLASSES
NUM_BOX_CHANNELS = NUM_ANCHORS * 7
NUM_DIR_CHANNELS = NUM_ANCHORS * NUM_DIR_BINS

ONNX_OUTPUT_SHAPES = {
    'cls_preds': (1, FEAT_Y, FEAT_X, NUM_CLS_CHANNELS),
    'box_preds': (1, FEAT_Y, FEAT_X, NUM_BOX_CHANNELS),
    'dir_cls_preds': (1, FEAT_Y, FEAT_X, NUM_DIR_CHANNELS),
}

VOXEL_FEATURE_CHANNELS = 10

MODEL_TAG = 'pointpillar_v2_jrdb_v2_bs8'
